# Generated by Django 3.0.14 on 2021-12-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
                ('pub_date', models.DateField()),
            ],
            options={
                'ordering': ['comments', 'pub_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('recipe_type', models.CharField(max_length=30)),
                ('views', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('rating', models.ManyToManyField(to='recipesBackend.Rating')),
            ],
            options={
                'ordering': ['recipe_type', 'views'],
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesBackend.User'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('receiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='recipesBackend.User')),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='recipesBackend.User')),
            ],
            options={
                'ordering': ['message', 'pub_date'],
            },
        ),
    ]
